### ISSUE TITLE
Can't open at Chrome

### ISSUE THREAD

**Issue by yongcang** [bang590/JSPatchConvertor#12]
I download the project,and open the index.html through Safari, it's OK. But using Chrome, I couldn't open it. Only showing loading...

**Comment by yongcang** [comment]
I have get it. I need to build a server to open this html file.

**Comment by bang590** [comment]
Yes.
You can try the Mac Application https://github.com/DevSonw/JSPatchConvertor/blob/gh-pages/JSPatchConvertor.zip
