### ISSUE TITLE
It did not work when I change (__bridge ID) type conversion to JS code

### ISSUE THREAD

**Issue by LXManMan** [bang590/JSPatchConvertor#16]
self.view.layer.contents = (__bridge id)[UIImage imageNamed:@"gougou.jpg"].CGImage;
About top code ,how can I deal with the situation

**Comment by bang590** [comment]
try `UIImage. imageNamed("gougou.jpg").CGImage()`

**Comment by LXManMan** [comment]
thank you ，but I heard that JSPatch is 

prohibit
